version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/project/develop/git-action-test/
   
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
  
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
